#
# Copyright Â© 2016-2020 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2.2'

services:
  kafka:
    restart: always
    image: "wurstmeister/kafka:2.13-2.6.0"
    ports:
      - "9092:9092"
    env_file:
      - kafka.env
    depends_on:
      - zookeeper
  tb-js-executor:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-core1:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
      - redis
  tb-core2:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
      - redis
  tb-rule-engine1:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
      - redis
  tb-rule-engine2:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
      - redis
  tb-mqtt-transport1:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-mqtt-transport2:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-http-transport1:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-http-transport2:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
  tb-coap-transport:
    env_file:
      - queue-kafka.env
    depends_on:
      - kafka
