route:
  receiver: 'slack'

receivers:
  - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             username: '<username>'
#             channel: '#<channel-name>'
#             api_url: '<incomming-webhook-url>'
