name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: wasslz-dev
    environment: dev
    env:
      JAVA_VERSION: 17
      NODE_VERSION: lts/*  # Latest LTS version (Node 18)
      IMAGE_NAME: thingsboard
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      # Checkout the code
      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: true
      #     android: true
      #     dotnet: true
      #     haskell: true
      #     large-packages: true
      #     docker-images: true
      #     swap-storage: true
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Cache npm packages
      - name: Cache npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-global-
            ${{ runner.os }}-

      # Install global npm packages
      - name: Install Global npm Packages
        run: |
          npm config set prefer-offline true
          npm config set progress false
          npm install -g cross-env webpack

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      # Debug cache keys (optional)
      - name: Debug Cache Keys
        run: |
          echo "NPM Cache Key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') }}"
          echo "Maven Cache Key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build the project with Maven
      - name: Build the project
        run: |
          mvn license:format install -DskipTests -Ddockerfile.skip=false -Ppush-docker-image

      # List Docker images for verification
      - name: List Docker images
        run: |
          docker image ls
