name: Remote Workflow Dispatch

on:
  push:
    branches:
      - master

env:
  REMOTE_REPOSITORY: valuabletouch/thingsboard-docker

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Send Dispatch Request
        run: |
          curl \
            --request POST https://api.github.com/repos/${{ env.REMOTE_REPOSITORY }}/dispatches \
            --header 'Content-Type: application/json' \
            --header 'Accept: application/vnd.github.v3+json' \
            --data '{"event_type": "dispatch", "client_payload": { "repository": "${{ env.GITHUB_REPOSITORY }}" }}'
